### ISSUE TITLE
Why the U*R*ERE*UF*RF*re8V*R* is it 34% Lua?

### ISSUE THREAD

**Issue by not-samurai** [Yaboi-solo/Aether-Engine#1]
Shadow here, title's kinda self-explanatory.

**Comment by Yaboi-solo** [comment]
Well, not really and 'issue' but it's because I'm using Premake 5.0, which is - I can upload just the main source files and run a command. The command finds the file called 'premake5.lua' and it takes the, you can say, instructions and generates project files.
This way its compatible with many IDEs and, IN THE FUTURE, cross-platform

**Comment by not-samurai** [comment]
I actually wonder if I could port it to Linux using Premake. That would be cool.
